
#GET
GET https://nestportal.onrender.com/campus

### POST campus
POST https://nestportal.onrender.com/campus
Content-Type: application/json

{
    "id":1,
    "name": "qwerty",
    "address": "qwerty address"
}