

# get programs

GET https://node-mysql-signup-verification-api.onrender.com/external/get-programs-active


#GET
GET http://localhost:3000/department/

### POST campus
POST https://nestportal.onrender.com/campus
Content-Type: application/json

{
    "id":1,
    "name": "qwerty",
    "address": "qwerty address"
}


